#!/bin/bash

EXTRA_ARGS=$@

#
# Configure script for an MPI DEBUG build of the TriBITS project & package.
#
# This script will work in any platform where the MPI compiler wrappers are in
# the default path.
#
# This script must be symbolically linked in for it to find the path back to
# the local TriBITS repo.
#

if [ "$TRIBITS_BASE_DIR" == "" ] ; then
  _ABS_FILE_PATH=`readlink -f $0`
  _SCRIPT_DIR=`dirname $_ABS_FILE_PATH`
  TRIBITS_BASE_DIR=$_SCRIPT_DIR/../..
fi

TRIBITS_BASE_DIR_ABS=$(readlink -f $TRIBITS_BASE_DIR)
echo "TRIBITS_BASE_DIR_ABS = $TRIBITS_BASE_DIR_ABS"

cmake \
-D CMAKE_BUILD_TYPE:STRING="DEBUG" \
-D TPL_ENABLE_MPI:BOOL=ON \
-D PYTHON_EXECUTABLE=/usr/bin/python2.6 \
-D TriBITS_ENABLE_Fortran:BOOL=ON \
-D TriBITS_ENABLE_TESTS:BOOL=ON \
-D TriBITS_ENABLE_CONFIGURE_TIMING:BOOL=ON \
$EXTRA_ARGS \
${TRIBITS_BASE_DIR_ABS}

