INCLUDE("${CMAKE_CURRENT_LIST_DIR}/../TribitsProjCTestDriver.cmake")

#
# Set the options specific to this build case
#

SET(COMM_TYPE SERIAL)
SET(BUILD_TYPE DEBUG)
SET(BUILD_DIR_NAME ${COMM_TYPE}_${BUILD_TYPE}_TravisCI)
SET(CTEST_SITE TravisCI)
SET(CTEST_TEST_TIMEOUT 60)
SET(CTEST_DO_UPDATES OFF)

SET_DEFAULT_AND_FROM_ENV( CTEST_BUILD_FLAGS "-j1 -i" )

SET_DEFAULT_AND_FROM_ENV( CTEST_PARALLEL_LEVEL "1" )

SET( EXTRA_CONFIGURE_OPTIONS
  "-DBUILD_SHARED_LIBS:BOOL=ON"
  "-DCMAKE_BUILD_TYPE=DEBUG"
  "-DCMAKE_C_COMPILER=gcc"
  "-DCMAKE_CXX_COMPILER=g++"
  "-DCMAKE_Fortran_COMPILER=gfortran"
  "-DTriBITS_ENABLE_Fortran=ON"
  "-DTriBITS_CTEST_DRIVER_COVERAGE_TESTS=TRUE"
  "-DTriBITS_CTEST_DRIVER_MEMORY_TESTS=TRUE"
  "-DTriBITS_ENABLE_REAL_GIT_CLONE_TESTS=TRUE"
  "-DTriBITS_TRACE_ADD_TEST=ON"
  "-DTriBITS_SHOW_TEST_START_END_DATE_TIME=ON"
  "-DTriBITS_HOSTNAME=${CTEST_SITE}"
  )

SET(CTEST_TEST_TYPE Continuous)

#
# Run the CTest driver and submit to CDash
#

TRIBITS_PROJ_CTEST_DRIVER()
