# @HEADER
# ************************************************************************
#
#            TriBITS: Tribal Build, Integrate, and Test System
#                    Copyright 2013 Sandia Corporation
#
# Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
# the U.S. Government retains certain rights in this software.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
# 1. Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# 3. Neither the name of the Corporation nor the names of the
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY SANDIA CORPORATION "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL SANDIA CORPORATION OR THE
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# ************************************************************************
# @HEADER


INCLUDE(${CMAKE_CURRENT_LIST_DIR}/TribitsAdjustPackageEnablesHelpers.cmake)



#####################################################################
#
# Unit tests for code in TribitsAdjustPackageEnables.cmake
#
#####################################################################


#
# A) Test enabled/disable logic
#


FUNCTION(UNITTEST_ENABLE_NO_PACKAGES)

  MESSAGE("\n***")
  MESSAGE("*** Test enabling no packages (the default)")
  MESSAGE("***\n")

  # Debugging
  #SET(${PROJECT_NAME}_VERBOSE_CONFIGURE ON)

  UNITTEST_HELPER_READ_AND_PROCESS_PACKAGES()

  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_TPLS "MPI;BLAS;LAPACK;Boost")
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_TPLS 4)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_PACKAGES "Teuchos;RTOp;Ex2Package1;Ex2Package2")
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_PACKAGES 4)

#  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_DEFINED_TPLS "MPI;BLAS;LAPACK;Boost")
#  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_DEFINED_TPLS 4)
#  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_DEFINED_INTERNAL_PACKAGES "Teuchos;RTOp;Ex2Package1;Ex2Package2")
#  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_DEFINED_INTERNAL_PACKAGES 4)
#  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ALL_DEFINED_PACKAGES "MPI;BLAS;LAPACK;Boost;Teuchos;RTOp;Ex2Package1;Ex2Package2")
#  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_ALL_DEFINED_PACKAGES 8)

  UNITTEST_COMPARE_CONST(TPL_ENABLE_MPI "")
  UNITTEST_COMPARE_CONST(TPL_ENABLE_BLAS "")
  UNITTEST_COMPARE_CONST(TPL_ENABLE_LAPACK "")
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Teuchos "")
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_RTOp "")
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Ex2Package1 "")
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Ex2Package2 "")

ENDFUNCTION()


FUNCTION(UNITTEST_ENABLE_ALL_PACKAGES)

  MESSAGE("\n***")
  MESSAGE("*** Test enabling all packages")
  MESSAGE("***\n")

  # Debugging
  #SET(${PROJECT_NAME}_VERBOSE_CONFIGURE ON)
  #SET(TRIBITS_PROCESS_PACKAGES_AND_DIRS_LISTS_VERBOSE ON)

  SET(${PROJECT_NAME}_ENABLE_ALL_PACKAGES ON)

  UNITTEST_HELPER_READ_AND_PROCESS_PACKAGES()

  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_PACKAGES 4)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_TPLS 4)
  UNITTEST_COMPARE_CONST(TPL_ENABLE_MPI "")
  UNITTEST_COMPARE_CONST(TPL_ENABLE_BLAS ON)
  UNITTEST_COMPARE_CONST(TPL_ENABLE_LAPACK ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Teuchos ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_RTOp ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Ex2Package1 ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Ex2Package2 "")

ENDFUNCTION()


FUNCTION(UNITTEST_ENABLE_ALL_PACKAGES_ST)

  MESSAGE("\n***")
  MESSAGE("*** Test enabling all secondary tested packages")
  MESSAGE("***\n")

  # Debugging
  #SET(${PROJECT_NAME}_VERBOSE_CONFIGURE ON)

  SET(${PROJECT_NAME}_ENABLE_ALL_PACKAGES ON)
  SET(${PROJECT_NAME}_ENABLE_SECONDARY_TESTED_CODE ON)

  UNITTEST_HELPER_READ_AND_PROCESS_PACKAGES()

  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_PACKAGES 4)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_TPLS 4)
  UNITTEST_COMPARE_CONST(TPL_ENABLE_MPI "")
  UNITTEST_COMPARE_CONST(TPL_ENABLE_BLAS ON)
  UNITTEST_COMPARE_CONST(TPL_ENABLE_LAPACK ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Teuchos ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_RTOp ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Ex2Package1 ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Ex2Package2 ON)

ENDFUNCTION()


#
# B) Test generation of export file information
#


FUNCTION(UNITTEST_ENABLE_ALL_GENERATE_EXPORT_DEPS)

  MESSAGE("\n***")
  MESSAGE("*** Test generation of export dependencies enabling all PT")
  MESSAGE("***\n")

  # Debugging
  #SET(${PROJECT_NAME}_VERBOSE_CONFIGURE ON)
  #SET(${PROJECT_NAME}_DUMP_PACKAGE_DEPENDENCIES ON)

  SET(${PROJECT_NAME}_ENABLE_ALL_PACKAGES ON)
  SET(${PROJECT_NAME}_GENERATE_EXPORT_FILE_DEPENDENCIES ON)

  UNITTEST_HELPER_READ_AND_PROCESS_PACKAGES()

  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_PACKAGES 4)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_TPLS 4)
  UNITTEST_COMPARE_CONST(Teuchos_FULL_ENABLED_DEP_PACKAGES "")
  UNITTEST_COMPARE_CONST(RTOp_FULL_ENABLED_DEP_PACKAGES "Teuchos")
  UNITTEST_COMPARE_CONST(Ex2Package1_FULL_ENABLED_DEP_PACKAGES "Teuchos")
  UNITTEST_COMPARE_CONST(Ex2Package2_FULL_ENABLED_DEP_PACKAGES "")

ENDFUNCTION()


FUNCTION(UNITTEST_ENABLE_ALL_ST_GENERATE_EXPORT_DEPS)

  MESSAGE("\n***")
  MESSAGE("*** Test generation of export dependencies enabling all ST")
  MESSAGE("***\n")

  # Debugging
  #SET(${PROJECT_NAME}_VERBOSE_CONFIGURE ON)
  #SET(${PROJECT_NAME}_DUMP_PACKAGE_DEPENDENCIES ON)

  SET(${PROJECT_NAME}_ENABLE_ALL_PACKAGES ON)
  SET(${PROJECT_NAME}_ENABLE_SECONDARY_TESTED_CODE ON)
  SET(${PROJECT_NAME}_GENERATE_EXPORT_FILE_DEPENDENCIES ON)

  UNITTEST_HELPER_READ_AND_PROCESS_PACKAGES()

  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_PACKAGES 4)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_TPLS 4)
  UNITTEST_COMPARE_CONST(Teuchos_FULL_ENABLED_DEP_PACKAGES "")
  UNITTEST_COMPARE_CONST(RTOp_FULL_ENABLED_DEP_PACKAGES "Teuchos")
  UNITTEST_COMPARE_CONST(Ex2Package1_FULL_ENABLED_DEP_PACKAGES "Teuchos")
  UNITTEST_COMPARE_CONST(Ex2Package2_FULL_ENABLED_DEP_PACKAGES "Ex2Package1;Teuchos")

ENDFUNCTION()


FUNCTION(UNITTEST_ENABLE_ALL_ST_GENERATE_EXPORT_DEPS_ONLY_Ex2Package1)

  MESSAGE("\n***")
  MESSAGE("*** Test generation of export dependencies only up to Ex2Package1")
  MESSAGE("***\n")

  # Debugging
  #SET(${PROJECT_NAME}_VERBOSE_CONFIGURE ON)
  #SET(${PROJECT_NAME}_DUMP_PACKAGE_DEPENDENCIES ON)

  SET(${PROJECT_NAME}_ENABLE_ALL_PACKAGES ON)
  SET(${PROJECT_NAME}_ENABLE_SECONDARY_TESTED_CODE ON)
  SET(${PROJECT_NAME}_GENERATE_EXPORT_FILE_DEPENDENCIES ON)
  SET(${PROJECT_NAME}_GENERATE_EXPORT_FILES_FOR_ONLY_LISTED_SE_PACKAGES
    Ex2Package1 RTOp)

  UNITTEST_HELPER_READ_AND_PROCESS_PACKAGES()

  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_PACKAGES 4)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_TPLS 4)
  UNITTEST_COMPARE_CONST(Teuchos_FULL_ENABLED_DEP_PACKAGES "")
  UNITTEST_COMPARE_CONST(RTOp_FULL_ENABLED_DEP_PACKAGES "Teuchos")
  UNITTEST_COMPARE_CONST(Ex2Package1_FULL_ENABLED_DEP_PACKAGES "Teuchos")
  UNITTEST_COMPARE_CONST(Ex2Package2_FULL_ENABLED_DEP_PACKAGES "")

ENDFUNCTION()


FUNCTION(UNITTEST_ENABLE_RTOp_GENERATE_EXPORT_DEPS_ONLY_Ex2Package1)

  MESSAGE("\n***")
  MESSAGE("*** Test generation of export dependencies only up to Ex2Package1, only enable RTOp")
  MESSAGE("***\n")

  # Debugging
  #SET(${PROJECT_NAME}_VERBOSE_CONFIGURE ON)
  #SET(${PROJECT_NAME}_DUMP_PACKAGE_DEPENDENCIES ON)

  SET(${PROJECT_NAME}_ENABLE_RTOp ON)
  SET(${PROJECT_NAME}_ENABLE_SECONDARY_TESTED_CODE ON)
  SET(${PROJECT_NAME}_GENERATE_EXPORT_FILE_DEPENDENCIES ON)
  SET(${PROJECT_NAME}_GENERATE_EXPORT_FILES_FOR_ONLY_LISTED_SE_PACKAGES
    Ex2Package1 RTOp)

  UNITTEST_HELPER_READ_AND_PROCESS_PACKAGES()

  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_PACKAGES 4)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_TPLS 4)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_RTOp "ON")
  UNITTEST_COMPARE_CONST(Teuchos_FULL_ENABLED_DEP_PACKAGES "")
  UNITTEST_COMPARE_CONST(RTOp_FULL_ENABLED_DEP_PACKAGES "Teuchos")
  UNITTEST_COMPARE_CONST(Ex2Package1_FULL_ENABLED_DEP_PACKAGES "")
  UNITTEST_COMPARE_CONST(Ex2Package2_FULL_ENABLED_DEP_PACKAGES "")

ENDFUNCTION()


FUNCTION(UNITTEST_ENABLE_Teuchos_GENERATE_EXPORT_DEPS_ONLY_Ex2Package1)

  MESSAGE("\n***")
  MESSAGE("*** Test generation of export dependencies only up to Ex2Package1, only enable Teuchos")
  MESSAGE("***\n")

  # Debugging
  #SET(${PROJECT_NAME}_VERBOSE_CONFIGURE ON)
  #SET(${PROJECT_NAME}_DUMP_PACKAGE_DEPENDENCIES ON)

  SET(${PROJECT_NAME}_ENABLE_Teuchos ON)
  SET(${PROJECT_NAME}_ENABLE_SECONDARY_TESTED_CODE ON)
  SET(${PROJECT_NAME}_GENERATE_EXPORT_FILE_DEPENDENCIES ON)
  SET(${PROJECT_NAME}_GENERATE_EXPORT_FILES_FOR_ONLY_LISTED_SE_PACKAGES
    Ex2Package1 RTOp)

  UNITTEST_HELPER_READ_AND_PROCESS_PACKAGES()

  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_PACKAGES 4)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_TPLS 4)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Teuchos "ON")
  UNITTEST_COMPARE_CONST(Teuchos_FULL_ENABLED_DEP_PACKAGES "")
  UNITTEST_COMPARE_CONST(RTOp_FULL_ENABLED_DEP_PACKAGES "")
  UNITTEST_COMPARE_CONST(Ex2Package1_FULL_ENABLED_DEP_PACKAGES "")
  UNITTEST_COMPARE_CONST(Ex2Package2_FULL_ENABLED_DEP_PACKAGES "")

ENDFUNCTION()


#
# C) Test primary meta-project package enable/disable logic
#


FUNCTION(UNITTEST_ENABLE_TRIBITS_IS_PRIMARY_META_PROJECT_PACKAGE)

  MESSAGE("\n***")
  MESSAGE("*** Unit testing primary meta-project packages, no Trilinos, enable all")
  MESSAGE("***\n")

  # Debugging
  #SET(${PROJECT_NAME}_VERBOSE_CONFIGURE ON)
  #SET(TRIBITS_PROCESS_PACKAGES_AND_DIRS_LISTS_VERBOSE ON)

  SET(${PROJECT_NAME}_ENABLE_ALL_PACKAGES ON)
  #SET(${PROJECT_NAME}_ENABLE_SECONDARY_TESTED_CODE ON)
  SET(Trilinos_NO_PRIMARY_META_PROJECT_PACKAGES ON)

  UNITTEST_HELPER_READ_AND_PROCESS_PACKAGES()

  TRIBITS_IS_PRIMARY_META_PROJECT_PACKAGE(Teuchos  Teuchos_is_PMP)
  UNITTEST_COMPARE_CONST(Teuchos_is_PMP  FALSE)

  TRIBITS_IS_PRIMARY_META_PROJECT_PACKAGE(RTOp  RTOp_is_PMP)
  UNITTEST_COMPARE_CONST(RTOp_is_PMP  FALSE)

  TRIBITS_IS_PRIMARY_META_PROJECT_PACKAGE(Ex2Package1  Ex2Package1_is_PMP)
  UNITTEST_COMPARE_CONST(Ex2Package1_is_PMP  TRUE)

  TRIBITS_IS_PRIMARY_META_PROJECT_PACKAGE(Ex2Package2  Ex2Package2_is_PMP)
  UNITTEST_COMPARE_CONST(Ex2Package2_is_PMP  TRUE)

  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_PACKAGES 4)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_TPLS 4)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Teuchos ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_RTOp "")
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Ex2Package1 ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Ex2Package2 "")

ENDFUNCTION()


FUNCTION(UNITTEST_ENABLE_TRIBITS_IS_PRIMARY_META_PROJECT_PACKAGE_EXCLUDE_RTOP_ST)

  MESSAGE("\n***")
  MESSAGE("*** Unit testing primary meta-project packages, no Trilinos, exclude RTOp, enable all ST")
  MESSAGE("***\n")

  # Debugging
  #SET(${PROJECT_NAME}_VERBOSE_CONFIGURE ON)
  #SET(TRIBITS_PROCESS_PACKAGES_AND_DIRS_LISTS_VERBOSE ON)

  SET(${PROJECT_NAME}_ENABLE_ALL_PACKAGES ON)
  SET(${PROJECT_NAME}_ENABLE_SECONDARY_TESTED_CODE ON)
  SET(Trilinos_NO_PRIMARY_META_PROJECT_PACKAGES ON)
  SET(Trilinos_NO_PRIMARY_META_PROJECT_PACKAGES_EXCEPT  RTOp)

  UNITTEST_HELPER_READ_AND_PROCESS_PACKAGES()

  TRIBITS_IS_PRIMARY_META_PROJECT_PACKAGE(Teuchos  Teuchos_is_PMP)
  UNITTEST_COMPARE_CONST(Teuchos_is_PMP  FALSE)

  TRIBITS_IS_PRIMARY_META_PROJECT_PACKAGE(RTOp  RTOp_is_PMP)
  UNITTEST_COMPARE_CONST(RTOp_is_PMP  TRUE)

  TRIBITS_IS_PRIMARY_META_PROJECT_PACKAGE(Ex2Package1  Ex2Package1_is_PMP)
  UNITTEST_COMPARE_CONST(Ex2Package1_is_PMP  TRUE)

  TRIBITS_IS_PRIMARY_META_PROJECT_PACKAGE(Ex2Package2  Ex2Package2_is_PMP)
  UNITTEST_COMPARE_CONST(Ex2Package2_is_PMP  TRUE)

  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_PACKAGES 4)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_NUM_TPLS 4)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Teuchos ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_RTOp ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Ex2Package1 ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Ex2Package2 ON)

ENDFUNCTION()


FUNCTION(UNITTEST_ENABLE_TRIBITS_IS_PRIMARY_META_PROJECT_PACKAGE_ENABLE_Teuchos_FORWARD)

  MESSAGE("\n***")
  MESSAGE("*** Unit testing primary meta-project packages, enable Teuchos, enable forward")
  MESSAGE("***\n")

  # Debugging
  #SET(${PROJECT_NAME}_VERBOSE_CONFIGURE ON)
  #SET(TRIBITS_PROCESS_PACKAGES_AND_DIRS_LISTS_VERBOSE ON)

  #SET(${PROJECT_NAME}_ENABLE_SECONDARY_TESTED_CODE ON)
  SET(Trilinos_NO_PRIMARY_META_PROJECT_PACKAGES ON)
  SET(Trilinos_NO_PRIMARY_META_PROJECT_PACKAGES_EXCEPT  RTOp)

  SET(${PROJECT_NAME}_ENABLE_TESTS ON)
  SET(${PROJECT_NAME}_ENABLE_ALL_FORWARD_DEP_PACKAGES ON)
  SET(${PROJECT_NAME}_ENABLE_Teuchos ON)

  UNITTEST_HELPER_READ_AND_PROCESS_PACKAGES()

  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Teuchos ON)
  UNITTEST_COMPARE_CONST(Teuchos_ENABLE_TESTS "")
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_RTOp ON)
  UNITTEST_COMPARE_CONST(RTOp_ENABLE_TESTS ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Ex2Package1 ON)
  UNITTEST_COMPARE_CONST(Ex2Package1_ENABLE_TESTS ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Ex2Package2 "")
  UNITTEST_COMPARE_CONST(Ex2Package2_ENABLE_TESTS "")

ENDFUNCTION()


FUNCTION(UNITTEST_ENABLE_TRIBITS_IS_PRIMARY_META_PROJECT_PACKAGE_ENABLE_Teuchos_Tests_RTOp_FORWARD)

  MESSAGE("\n***")
  MESSAGE("*** Unit testing primary meta-project packages, enable Teuchos tests, enable RTOp, enable forward")
  MESSAGE("***\n")

  # Debugging
  #SET(${PROJECT_NAME}_VERBOSE_CONFIGURE ON)
  #SET(TRIBITS_PROCESS_PACKAGES_AND_DIRS_LISTS_VERBOSE ON)

  #SET(${PROJECT_NAME}_ENABLE_SECONDARY_TESTED_CODE ON)
  SET(Trilinos_NO_PRIMARY_META_PROJECT_PACKAGES ON)
  SET(Trilinos_NO_PRIMARY_META_PROJECT_PACKAGES_EXCEPT  RTOp)

  SET(${PROJECT_NAME}_ENABLE_TESTS ON)
  SET(${PROJECT_NAME}_ENABLE_ALL_FORWARD_DEP_PACKAGES ON)

  SET(${PROJECT_NAME}_ENABLE_Teuchos ON)
  SET(Teuchos_ENABLE_TESTS ON)  # Must be explicitly turned on!

  SET(${PROJECT_NAME}_ENABLE_RTOp ON)
  # Tests will get turned on automatically because RTOp is a it is a PMPP

  UNITTEST_HELPER_READ_AND_PROCESS_PACKAGES()

  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Teuchos ON)
  UNITTEST_COMPARE_CONST(Teuchos_ENABLE_TESTS ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_RTOp ON)
  UNITTEST_COMPARE_CONST(RTOp_ENABLE_TESTS ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Ex2Package1 ON)
  UNITTEST_COMPARE_CONST(Ex2Package1_ENABLE_TESTS ON)
  UNITTEST_COMPARE_CONST(${PROJECT_NAME}_ENABLE_Ex2Package2 "")
  UNITTEST_COMPARE_CONST(Ex2Package2_ENABLE_TESTS "")

ENDFUNCTION()


#####################################################################
#
# Execute the unit tests
#
#####################################################################

# Assume that all unit tests will pass by default
GLOBAL_SET(UNITTEST_OVERALL_PASS TRUE)
GLOBAL_SET(UNITTEST_OVERALL_NUMPASSED 0)
GLOBAL_SET(UNITTEST_OVERALL_NUMRUN 0)

# A) Test enabled/disable logic
UNITTEST_ENABLE_NO_PACKAGES()
UNITTEST_ENABLE_ALL_PACKAGES()
UNITTEST_ENABLE_ALL_PACKAGES_ST()

# B) Test generation of export file information
UNITTEST_ENABLE_ALL_GENERATE_EXPORT_DEPS()
UNITTEST_ENABLE_ALL_ST_GENERATE_EXPORT_DEPS()
UNITTEST_ENABLE_ALL_ST_GENERATE_EXPORT_DEPS_ONLY_Ex2Package1()
UNITTEST_ENABLE_RTOp_GENERATE_EXPORT_DEPS_ONLY_Ex2Package1()
UNITTEST_ENABLE_Teuchos_GENERATE_EXPORT_DEPS_ONLY_Ex2Package1()

# C) Test primary meta-project package enable/disable logic
UNITTEST_ENABLE_TRIBITS_IS_PRIMARY_META_PROJECT_PACKAGE()
UNITTEST_ENABLE_TRIBITS_IS_PRIMARY_META_PROJECT_PACKAGE_EXCLUDE_RTOP_ST()
UNITTEST_ENABLE_TRIBITS_IS_PRIMARY_META_PROJECT_PACKAGE_ENABLE_Teuchos_FORWARD()
UNITTEST_ENABLE_TRIBITS_IS_PRIMARY_META_PROJECT_PACKAGE_ENABLE_Teuchos_Tests_RTOp_FORWARD()

# Pass in the number of expected tests that must pass!
UNITTEST_FINAL_RESULT(97)