IF ("${PROJECT_NAME}" STREQUAL "")
  MESSAGE(FATAL_ERROR "ERROR: Must set 'PROJECT_NAME' before including this file" )
ENDIF()

IF ("${${PROJECT_NAME}_SOURCE_DIR}" STREQUAL "")
  MESSAGE(FATAL_ERROR "ERROR: ${PROJECT_NAME}_SOURCE_DIR not set!"
    "Must call PROJECT(${PROJECT_NAME} NONE) before including this file!" )
ENDIF()

# Set default location for ${PROJECT_NAME}_TRIBITS_DIR
SET(${PROJECT_NAME}_TRIBITS_DIR_DEFAULT "${CMAKE_CURRENT_LIST_DIR}" )

SET(${PROJECT_NAME}_TRIBITS_DIR
   "${${PROJECT_NAME}_TRIBITS_DIR_DEFAULT}"  CACHE  FILEPATH
  "TriBITS base directory)")

INCLUDE("${${PROJECT_NAME}_TRIBITS_DIR}/TriBITS.cmake")
