#!/bin/bash

../../../Trilinos/TriBITS/dev_testing/generic/do-configure-mpi-debug \
-DRULE_LAUNCH_COMPILE=ccache \
-DCTEST_PARALLEL_LEVEL=16 \
-DTriBITS_CTEST_DRIVER_COVERAGE_TESTS=TRUE \
-DTriBITS_CTEST_DRIVER_MEMORY_TESTS=TRUE \
-DTriBITS_ENABLE_CONFIGURE_TIMING=ON \
-DTribitsExProj_INSTALL_OWNING_GROUP=wg-atdm-devops \
-DTriBITS_ENABLE_REAL_GIT_CLONE_TESTS=ON \
-DDART_TESTING_TIMEOUT=60 \
"$@"

#-DTriBITS_CTEST_DRIVER_COVERAGE_TESTS=TRUE \
#-DTriBITS_CTEST_DRIVER_MEMORY_TESTS=TRUE \

# To submit to testing.sandia.gov/cdash set:
#
#   -DTriBITS_CTEST_DRIVER_SUBMIT_TO=TESTING_SANDIA_CDASH

# To submit to testing-dev.sandia.gov/cdash set:
#
#   -DTriBITS_CTEST_DRIVER_SUBMIT_TO=TESTING_DEV_SANDIA_CDASH

# To submit to exp.cdash.org set:
#
#   -DTriBITS_CTEST_DRIVER_SUBMIT_TO=EXP_CDASH

# To submot to arbitary CDash site (e.g. testing-dev.sandia.gov/cdash) set:
#
#   -DTriBITS_CTEST_DRIVER_SUBMIT_TO=CUSTOM
#   -DTriBITS_CTEST_DRIVER_SUBMIT_DROP_SITE=testing-dev.sandia.gov
#   -DTriBITS_CTEST_DRIVER_SUBMIT_DROP_LOCATION="/cdash/submit.php?project=TribitsExProj"

# NOTE: Add -DTriBITS_ENABLE_REAL_GIT_CLONE_TESTS=ON to test cloning TriBITS
# Exmaple repos and testing the clone features of the various tools.  To get
# this to work on SNL machines, one may need to switch from
# 'https://github.com/' to 'git@github.com:' using:
#
#  export TribitsExMetaProj_GIT_URL_REPO_BASE=git@github.com:tribits/
#
# before configuring.

