SET(TRIBITS_DIR "" CACHE FILEPATH "Must be set on commandline!")

SET(${PROJECT_NAME}_TRACE_ADD_TEST TRUE)
SET(${PROJECT_NAME}_TRIBITS_DIR ${TRIBITS_DIR}) 
SET(PACKAGE_NAME ${PROJECT_NAME})
SET(${PACKAGE_NAME}_ENABLE_TESTS TRUE)
SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH}
  ${TRIBITS_DIR}/core/utils
  ${TRIBITS_DIR}/core/package_arch )
INCLUDE(TribitsAddAdvancedTest)
INCLUDE(CTest)
ENABLE_TESTING()
